### PR TITLE
Fix SSR

### PR DESCRIPTION
**Pull request by edoroshenko**
1. Set DEFAULT_COLUMNS_COUNT to the state on init
2. Cover SSR with unit test

### CODE REVIEW

**Comment by xuopled** [comment]
Hi @edoroshenko, sorry for the delay. Thank you very much for fixing SSR. It's almost OK for me. Could you remove the `package-lock.json` I use yarn for this project so I don't need it.

After that, I will merge it. 

Thank you

**Comment by xuopled** [comment]
Could you also squash your commits to have only one commit ? Thank you very much for your contribution

**Comment by edoroshenko** [comment]
Hi @xuopled !
Done!

**Comment by xuopled** [comment]
Thank you very much

**Comment by xuopled** [comment]
closes #9

**Pull request merged**
